import "./app.scss";
import React, { useEffect, useState } from "react";
import "bootstrap/dist/css/bootstrap.min.css";
import { Canvas } from "@react-three/fiber";
import { GlassPanel, Model, Stand } from "./Model";
import Forum from './Form'
import Phone from "./Phone";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function App() {
  const [isAnimating, setIsAnimating] = useState(false)

  return (
    <main>
      <section className="contentwrapper container p-sm-0">
        <div className="row">
          <div className="col-lg-6 col-12 p-0">
            <Forum animate={isAnimating} setAnimate={setIsAnimating}/>
          </div>
          <div className="col-lg-6 col-12 p-0 d-none d-lg-block">
            <Phone animate={isAnimating} setAnimate={setIsAnimating}/>
          </div>
        </div>
      </section>
    </main>
  );
}

export default App;
